/********************************************************************
**       This head file is generated by program,                   **
**            Please do not change it directly.                    **
********************************************************************/

#ifndef TBUS_MACROS_H_
#define TBUS_MACROS_H_


/*   User defined includes.   */


/*   User defined macros.   */
#define TBUS_MAX_ADDR_STRING_LEN                         	256 	/* max length of comunication address for process */
#define TBUS_MAX_ADDR_TEMPLET_STRING_LEN                 	256 	/* max length of address templet string */
#define TBUS_MAX_HOST_URL_LEN                            	128 	/* max number of channels in one host machine */
#define TBUS_MAX_CHANNEL_NUM_PREHOST                     	3000 	/* max number of channels in one host machine */
#define TBUS_MAX_RELAY_NUM_PREHOST                       	3000 	/* max number of relay channels in one host machine */
#define TBUS_MAX_AUTOMATIC_RELAY_NUM                     	262144 	/* max automatic relay num per business */
#define TBUS_MAX_KEY_STRING_LEN                          	256 	/* max length of discription */
#define TBUS_MODE_DISABLE                                	1 	/*  */
#define TBUS_MODE_ENABLE                                 	2 	/*  */
#define TBUS_PEER_CTRL_ONE                               	0 	/*  */
#define TBUS_PEER_CTRL_ALL                               	1 	/*  */
#define TBUS_CONF_MAX_FILE_NAME                          	1024
#define TBUS_CHANNEL_DEFAULT_PRIORITY                    	8
#define TBUSD_DEFAULT_PKG_MAX_SIZE                       	131072 	/* 缺省支持的数据包最大长度64K */
#define TBUSD_DEFAULT_SOCKET_BUFF                        	131072 	/* socket链接缺省缓冲区大小 */
#define TBUSD_DEFAULT_IDLE_COUNT                         	2
#define TBUSD_DEFAULT_HOSTS_REFRESH_GAP                  	30 	/* 缺省Hosts刷新间隔，单位为秒 */
#define TBUSD_DEFAULT_TOKEN_LEN                          	64 	/* tbusd default token len */



#endif /* TBUS_MACROS_H_ */
