/* This file is generated by tdr. */
/* No manual modification is permitted. */

/* metalib version: 10 */
/* metalib md5sum: 6f5632e4a08068fb87f5e36963885eb8 */

/* creation time: Tue Jun  4 14:17:59 2019 */
/* tdr version: 2.7.26, build at 20171102 */

#ifndef BlackBoard_metalib_h_
#define BlackBoard_metalib_h_

namespace BlackBoard
{


class MetaLib
{
    public:
        static int getVersion()
        {
            return 10;
        }

        static const char* getName()
        {
            return "BlackBoard";
        }

        static const char* getMd5Sum()
        {
            return "6f5632e4a08068fb87f5e36963885eb8";
        }

        static const char* getTdrVersion()
        {
            return "2.7.26, build at 20171102";
        }
};


}
#endif
