/* This file is generated by tdr. */
/* No manual modification is permitted. */

/* metalib version: 10 */
/* metalib md5sum: 6f5632e4a08068fb87f5e36963885eb8 */

/* creation time: Tue Jun  4 14:17:59 2019 */
/* tdr version: 2.7.26, build at 20171102 */

#ifndef BlackBoard_h_
#define BlackBoard_h_

#include "TdrBuf.h"
#include "TdrError.h"
#include "TdrBufUtil.h"


namespace BlackBoard
{

using tsf4g_tdr::TdrError;
using tsf4g_tdr::TdrReadBuf;
using tsf4g_tdr::TdrWriteBuf;


#pragma pack(1)


class BB_ServerTest
{
    public: /* members */
        int32_t iTestKeyNum; //
        int32_t iTestKey1; //
        int32_t iTestKey2; //
        int32_t iTestKey3; //

    public: /* methods */
        TdrError::ErrorType construct();

        TdrError::ErrorType pack(TdrWriteBuf& destBuf, unsigned cutVer = 0) const;
        TdrError::ErrorType pack(char* buffer, size_t size, size_t* usedSize = NULL, unsigned cutVer = 0) const;

        TdrError::ErrorType unpack(TdrReadBuf& srcBuf, unsigned cutVer = 0);
        TdrError::ErrorType unpack(const char* buffer, size_t size, size_t* usedSize = NULL, unsigned cutVer = 0);

        /* set indent = -1 to disable indent */
        TdrError::ErrorType visualize(TdrWriteBuf& destBuf, int indent = 0, char separator = '\n') const;
        TdrError::ErrorType visualize(char* buffer, size_t size, size_t* usedSize = NULL, int indent = 0, char separator = '\n') const;
        const char* visualize_ex(TdrWriteBuf& destBuf, int indent = 0, char separator = '\n') const;
        const char* visualize_ex(char* buffer, size_t size, size_t* usedSize = NULL, int indent = 0, char separator = '\n') const;


    public:
        /* version infomation */
        enum
        {
            BASEVERSION = 1,
            CURRVERSION = 1,
        };
};

typedef       BB_ServerTest          tagBB_ServerTest;
typedef       BB_ServerTest             BB_SERVERTEST;
typedef       BB_ServerTest*          LPBB_SERVERTEST;
typedef const BB_ServerTest*         LCPBB_SERVERTEST;


class BT_Monster_Normal
{
    public: /* members */
        int32_t iTargetActor; //
        int8_t chNeedGoHome; //
        float returnPos[3]; //
        float patrolPos[3]; //
        float fStandTime; //
        int32_t iPatrolType; //
        int8_t chNeedFlee; //

    public: /* methods */
        TdrError::ErrorType construct();

        TdrError::ErrorType pack(TdrWriteBuf& destBuf, unsigned cutVer = 0) const;
        TdrError::ErrorType pack(char* buffer, size_t size, size_t* usedSize = NULL, unsigned cutVer = 0) const;

        TdrError::ErrorType unpack(TdrReadBuf& srcBuf, unsigned cutVer = 0);
        TdrError::ErrorType unpack(const char* buffer, size_t size, size_t* usedSize = NULL, unsigned cutVer = 0);

        /* set indent = -1 to disable indent */
        TdrError::ErrorType visualize(TdrWriteBuf& destBuf, int indent = 0, char separator = '\n') const;
        TdrError::ErrorType visualize(char* buffer, size_t size, size_t* usedSize = NULL, int indent = 0, char separator = '\n') const;
        const char* visualize_ex(TdrWriteBuf& destBuf, int indent = 0, char separator = '\n') const;
        const char* visualize_ex(char* buffer, size_t size, size_t* usedSize = NULL, int indent = 0, char separator = '\n') const;


    public:
        /* version infomation */
        enum
        {
            BASEVERSION = 1,
            CURRVERSION = 1,
        };
};

typedef       BT_Monster_Normal          tagBT_Monster_Normal;
typedef       BT_Monster_Normal             BT_MONSTER_NORMAL;
typedef       BT_Monster_Normal*          LPBT_MONSTER_NORMAL;
typedef const BT_Monster_Normal*         LCPBT_MONSTER_NORMAL;


#pragma pack()

}
#endif
