/********************************************************************
**       This head file is generated by program,                   **
**            Please do not change it directly.                    **
********************************************************************/

#ifndef TLOG_PRIORITY_DEF_H_
#define TLOG_PRIORITY_DEF_H_


/*   User defined includes.   */


/*   User defined macros.   */

/* TLOG_PRIORITY*/
enum tagTLOG_PRIORITY 
{
    TLOG_PRIORITY_FATAL = 0, 
    TLOG_PRIORITY_ALERT = 100, 
    TLOG_PRIORITY_CRIT = 200, 
    TLOG_PRIORITY_ERROR = 300, 
    TLOG_PRIORITY_WARN = 400, 
    TLOG_PRIORITY_NOTICE = 500, 
    TLOG_PRIORITY_INFO = 600, 
    TLOG_PRIORITY_DEBUG = 700, 
    TLOG_PRIORITY_TRACE = 800, 
    TLOG_PRIORITY_NOTSET = 900, 
    TLOG_PRIORITY_UNKNOWN = 1000, 
    TLOG_PRIORITY_NULL = -1, 
};



#endif /* TLOG_PRIORITY_DEF_H_ */
