/********************************************************************
**       This head file is generated by program,                   **
**            Please do not change it directly.                    **
********************************************************************/

#ifndef TLOGNETDEF_H_
#define TLOGNETDEF_H_


/*   Define c types.   */
#ifndef TDR_CUSTOM_C_TYPES
#define TDR_CUSTOM_C_TYPES
    #include <stddef.h>
    #include <time.h>
    #include <sys/types.h>

    #if !defined(_WIN32) && !defined(_WIN64)

        #include <stdint.h>
        #include <inttypes.h>

    #else /*if !defined(_WIN32) && !defined(_WIN64)*/

        //The stdint declaras
        typedef  signed char  int8_t;
        typedef  short int16_t;
        typedef  int   int32_t;
        typedef unsigned char  uint8_t;
        typedef unsigned short uint16_t;
        typedef unsigned int   uint32_t;
        #if _MSC_VER >= 1300
            typedef unsigned long long 	uint64_t;
            typedef long long 	int64_t;
        #else /* _MSC_VER */
            typedef unsigned __int64	uint64_t;
            typedef __int64	int64_t;
        #endif /* _MSC_VER */

    #endif /*if !defined(_WIN32) && !defined(_WIN64)*/

    typedef int64_t tdr_longlong;
    typedef uint64_t tdr_ulonglong;
    typedef uint16_t tdr_wchar_t;  /**<Wchar基本数据类型*/
    typedef uint32_t tdr_date_t;	/**<data基本数据类型*/
    typedef uint32_t tdr_time_t;	/**<time基本数据类型*/
    typedef uint64_t tdr_datetime_t; /**<datetime基本数据类型*/
    typedef uint32_t tdr_ip_t;  /**<IPv4数据类型*/
#endif /*TDR_CUSTOM_C_TYPES*/


/*   User defined includes.   */


/*   User defined macros.   */
#define TLOGNET_URL_LEN                                  	128
#define TLOGNET_DEF_TIMEOUT                              	2000


/*   Structs/unions prototype.   */
struct tagTLOGDevNet;
typedef struct tagTLOGDevNet                                       	TLOGDEVNET;
typedef struct tagTLOGDevNet                                       	*LPTLOGDEVNET;

/*   Define structs/unions.   */
#pragma pack(1)

struct tagTLOGDevNet
{
    char szUrl[TLOGNET_URL_LEN];                     
    int32_t iBuffSize;                               
    int32_t iSendBuff;                               
    int32_t iRecvBuff;                               
    int32_t iAutoReconnect;                          
    int32_t iMaxRetry;                               
    int32_t iConnTimeout;                            
    int32_t iSendTimeout;                            
};

#pragma pack()


#endif /* TLOGNETDEF_H_ */
